apiVersion: v1
kind: Secret
metadata:
  name: {{ include "undeadapps.name" . }}Env
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  MANAGED_BY: !!str Ymxvaw==
  {{ if .Values.s3bucket.name }}S3_BUCKET: !!str {{ .Values.s3bucket.name | b64enc }}{{ end }}