apiVersion: v1
kind: Service
metadata:
  name: {{ include "undeadapps.name" . }}
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace }}
  {{- end }}
  labels:
    {{- include "undeadapps.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: svc
      protocol: TCP
      name: http
  selector:
    {{- include "undeadapps.selectorLabels" . | nindent 4 }}
