apiVersion: v2
name: undeadapps
description: An Opinionated Helm chart for Application Deployment on Kubernetes in AWS
type: application
version: 0.29.0
maintainers:
  - name: undeadops
    email: mitch@undeadops.xyz
    url: https://undeadops.xyz
