on:
  push:
    branches:
      - main

env:
  GHCR_IMAGE: ghcr.io/${{ github.repository_owner }}/undeadapps

jobs:
  build:
    name: publish gcr
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v3
        name: checkout repo

      - uses: azure/setup-helm@v3
        with:
          version: '3.12.0'
          token: ${{ secrets.GITHUB_TOKEN }} # only needed if version is 'latest'
        id: install

      - name: Push Helm chart to OCI compatible registry (Github)
        uses: bsord/helm-push@v4.2
        with:
         useOCIRegistry: true
         registry-url:  oci://ghcr.io/${{ github.repository }}
         access-token: ${{ secrets.REGISTRY_ACCESS_TOKEN }}
         force: true
         chart-folder: undeadapps/charts

