name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Bump version and push tag
        id: bump-version-tag
        uses: anothrNick/github-tag-action@1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_BRANCHES: main

      - name: Set up yq
        uses: frenck/action-setup-yq@v1.0.1

      - name: Update Chart versions
        run: |
          yq -i '.version="${{ steps.bump-version-tag.outputs.new_tag }}"' 'charts/undeadapps/Chart.yaml'

      - name: Commit Updated Chart.yaml
        uses: test-room-7/action-update-file@v1
        with:
          file-path: charts/undeadapps/Chart.yaml
          commit-msg: 'ci(Chart.yaml): update version for chart'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Package and Push a Helm Chart to GHCR
        uses: explorium-ai/package-helm-ghcr-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          gh-token: ${{ secrets.GITHUB_TOKEN }}
          gh-repo-owner: undeadops
          chart-path: ./charts/undeadapps

